---
title: "residuals_copula_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## DJIA,GSPC,NDX,GDAXI,FCHI,SSEC,SENSEX Analysis

https://github.com/cran/VineCopula - Copula family

```{r}

setwd('~/Documents/VaR')

prices <- read.csv('./data/StockIndexData.csv')

library(VineCopula)
library(copula)
library(tseries)

```



## DJIA,GSPC,NDX,GDAXI,FCHI,SSEC,SENSEX

```{r}

prices.DJIA <- prices[,c('DJIA')]

summary(prices.DJIA)

n <- length(prices.DJIA)
rtn.DJIA <- rep(0,n-1)

for(i in seq(n-1)){
  rtn.DJIA[i] <- log(prices.DJIA[i+1]/prices.DJIA[i]) * 100.
}

prices.GSPC <- prices[,c('GSPC')]

summary(prices.GSPC)

n <- length(prices.GSPC)
rtn.GSPC <- rep(0,n-1)

for(i in seq(n-1)){
  rtn.GSPC[i] <- log(prices.GSPC[i+1]/prices.GSPC[i]) * 100.
}

prices.NDX <- prices[,c('NDX')]

summary(prices.NDX)

n <- length(prices.NDX)
rtn.NDX <- rep(0,n-1)

for(i in seq(n-1)){
  rtn.NDX[i] <- log(prices.NDX[i+1]/prices.NDX[i]) * 100.
}

prices.GDAXI <- prices[,c('GDAXI')]

summary(prices.GDAXI)

n <- length(prices.GDAXI)
rtn.GDAXI <- rep(0,n-1)

for(i in seq(n-1)){
  rtn.GDAXI[i] <- log(prices.GDAXI[i+1]/prices.GDAXI[i]) * 100.
}

prices.FCHI <- prices[,c('FCHI')]

summary(prices.FCHI)

n <- length(prices.FCHI)
rtn.FCHI <- rep(0,n-1)

for(i in seq(n-1)){
  rtn.FCHI[i] <- log(prices.FCHI[i+1]/prices.FCHI[i]) * 100.
}

prices.SSEC <- prices[,c('SSEC')]

summary(prices.SSEC)

n <- length(prices.SSEC)
rtn.SSEC <- rep(0,n-1)

for(i in seq(n-1)){
  rtn.SSEC[i] <- log(prices.SSEC[i+1]/prices.SSEC[i]) * 100.
}

prices.SENSEX <- prices[,c('SENSEX')]

summary(prices.SENSEX)

n <- length(prices.SENSEX)
rtn.SENSEX <- rep(0,n-1)

for(i in seq(n-1)){
  rtn.SENSEX[i] <- log(prices.SENSEX[i+1]/prices.SENSEX[i]) * 100.
}

```

```{r}
rtn.DJIA.ar <- ar(rtn.DJIA, order.max = 1, method = 'ols')
rtn.DJIA.ar.resid.garch <- garch(rtn.DJIA.ar$resid[2:length(rtn.DJIA.ar$resid)],trace=FALSE)

rtn.GSPC.ar <- ar(rtn.GSPC, order.max = 1, method = 'ols')
rtn.GSPC.ar.resid.garch <- garch(rtn.GSPC.ar$resid[2:length(rtn.GSPC.ar$resid)],trace=FALSE)

rtn.NDX.1<-na.omit(rtn.NDX)
rtn.NDX.ar <- ar(rtn.NDX.1, order.max = 1, method = 'ols')
rtn.NDX.ar.resid.garch <- garch(rtn.NDX.ar$resid[2:length(rtn.NDX.ar$resid)],trace=FALSE)

rtn.GDAXI.1<-na.omit(rtn.GDAXI)
rtn.GDAXI.ar <- ar(rtn.GDAXI.1, order.max = 1, method = 'ols')
rtn.GDAXI.ar.resid.garch <- garch(rtn.GDAXI.ar$resid[2:length(rtn.GDAXI.ar$resid)],trace=FALSE)

rtn.FCHI.1<-na.omit(rtn.FCHI)
rtn.FCHI.ar <- ar(rtn.FCHI.1, order.max = 1, method = 'ols')
rtn.FCHI.ar.resid.garch <- garch(rtn.FCHI.ar$resid[2:length(rtn.FCHI.ar$resid)],trace=FALSE)

rtn.SSEC.1<-na.omit(rtn.SSEC)
rtn.SSEC.ar <- ar(rtn.SSEC.1, order.max = 1, method = 'ols')
rtn.SSEC.ar.resid.garch <- garch(rtn.SSEC.ar$resid[2:length(rtn.SSEC.ar$resid)],trace=FALSE)

rtn.SENSEX.1<-na.omit(rtn.SENSEX)
rtn.SENSEX.ar <- ar(rtn.SENSEX.1, order.max = 1, method = 'ols')
rtn.SENSEX.ar.resid.garch <- garch(rtn.SENSEX.ar$resid[2:length(rtn.SENSEX.ar$resid)],trace=FALSE)

rm(prices.DJIA, prices.GSPC, prices.NDX, prices.GDAXI, prices.FCHI,prices.SSEC, prices.SENSEX)
rm(rtn.DJIA, rtn.GSPC, rtn.NDX, rtn.GDAXI, rtn.FCHI,rtn.SSEC, rtn.SENSEX)
rm(rtn.NDX.1, rtn.GDAXI.1, rtn.FCHI.1,rtn.SSEC.1, rtn.SENSEX.1)

```

```{r}

std.residual.DJIA <- rtn.DJIA.ar$resid/sqrt(rtn.DJIA.ar.resid.garch$fitted.values)
std.residual.GSPC <- rtn.GSPC.ar$resid/sqrt(rtn.GSPC.ar.resid.garch$fitted.values)
std.residual.NDX <- rtn.NDX.ar$resid/sqrt(rtn.NDX.ar.resid.garch$fitted.values)
std.residual.GDAXI <- rtn.GDAXI.ar$resid/sqrt(rtn.GDAXI.ar.resid.garch$fitted.values)
std.residual.FCHI <- rtn.FCHI.ar$resid/sqrt(rtn.FCHI.ar.resid.garch$fitted.values)
std.residual.SSEC <- rtn.SSEC.ar$resid/sqrt(rtn.SSEC.ar.resid.garch$fitted.values)
std.residual.SENSEX <- rtn.SENSEX.ar$resid/sqrt(rtn.SENSEX.ar.resid.garch$fitted.values)

```

```{r}
rtns <- cbind(std.residual.DJIA[1067:4532],
              std.residual.GSPC[1067:4532],
              std.residual.NDX[2:3467],
              std.residual.GDAXI[953:4418],
              std.residual.FCHI[967:4432],
              std.residual.SSEC[658:4123],
              std.residual.SENSEX[674:4139]
              )


rm(std.residual.DJIA,std.residual.GSPC,std.residual.NDX,std.residual.GDAXI ,std.residual.FCHI,
   std.residual.SSEC,std.residual.SENSEX)

cor(rtns,method='pearson')
cor(rtns,method='kendall')
cor(rtns,method='spearman')

splom2(rtns)

g <- rtns[,1]
h<-hist(g, breaks=10, density=10, col="lightgray", xlab="Accuracy", main="Overall") 
    xfit<-seq(min(g),max(g),length=40) 
    yfit<-dnorm(xfit,mean=mean(g),sd=sd(g)) 
    yfit <- yfit*diff(h$mids[1:2])*length(g) 
    lines(xfit, yfit, col="black", lwd=2)
h

g <- rtns[,2]
h<-hist(g, breaks=10, density=10, col="lightgray", xlab="Accuracy", main="Overall") 
    xfit<-seq(min(g),max(g),length=40) 
    yfit<-dnorm(xfit,mean=mean(g),sd=sd(g)) 
    yfit <- yfit*diff(h$mids[1:2])*length(g) 
    lines(xfit, yfit, col="black", lwd=2)
h

g <- rtns[,3]
h<-hist(g, breaks=10, density=10, col="lightgray", xlab="Accuracy", main="Overall") 
    xfit<-seq(min(g),max(g),length=40) 
    yfit<-dnorm(xfit,mean=mean(g),sd=sd(g)) 
    yfit <- yfit*diff(h$mids[1:2])*length(g) 
    lines(xfit, yfit, col="black", lwd=2)
h

g <- rtns[,4]
h<-hist(g, breaks=10, density=10, col="lightgray", xlab="Accuracy", main="Overall") 
    xfit<-seq(min(g),max(g),length=40) 
    yfit<-dnorm(xfit,mean=mean(g),sd=sd(g)) 
    yfit <- yfit*diff(h$mids[1:2])*length(g) 
    lines(xfit, yfit, col="black", lwd=2)
h

g <- rtns[,5]
h<-hist(g, breaks=10, density=10, col="lightgray", xlab="Accuracy", main="Overall") 
    xfit<-seq(min(g),max(g),length=40) 
    yfit<-dnorm(xfit,mean=mean(g),sd=sd(g)) 
    yfit <- yfit*diff(h$mids[1:2])*length(g) 
    lines(xfit, yfit, col="black", lwd=2)
h

g <- rtns[,6]
h<-hist(g, breaks=10, density=10, col="lightgray", xlab="Accuracy", main="Overall") 
    xfit<-seq(min(g),max(g),length=40) 
    yfit<-dnorm(xfit,mean=mean(g),sd=sd(g)) 
    yfit <- yfit*diff(h$mids[1:2])*length(g) 
    lines(xfit, yfit, col="black", lwd=2)
h

g <- rtns[,7]
h<-hist(g, breaks=10, density=10, col="lightgray", xlab="Accuracy", main="Overall") 
    xfit<-seq(min(g),max(g),length=40) 
    yfit<-dnorm(xfit,mean=mean(g),sd=sd(g)) 
    yfit <- yfit*diff(h$mids[1:2])*length(g) 
    lines(xfit, yfit, col="black", lwd=2)
h

```



## DJIA,GSPC

```{r}
a <- rtns[,1]
b <- rtns[,2]

m <- pobs(as.matrix(cbind(a,b)))

u <- m[,1]
v <- m[,2]

mu.1 <- mean(a)
sd.1 <- sd(a)
mu.2 <- mean(b)
sd.2 <- sd(b)

plot(a,b,pch='.')
abline(lm(a~b),col='red',lwd=1)

```


```{r}

selectedCopula <- BiCopSelect(u,v,familyset=NA)

summary(selectedCopula)

```

```{r}
n.cop <- normalCopula(dim=2)
set.seed(500)
fit <- fitCopula(n.cop,m,method='ml')
coef(fit)

rho <- coef(fit)[1]

```

```{r}

copula_dist <- mvdc(copula=normalCopula(rho,dim=2), margins=c("norm","norm"),
                    paramMargins=list(list(mean=mu.1, sd=sd.1),
                                      list(mean=mu.2, sd=sd.2)))

sim <- rmvdc(copula_dist, 3466)

```

```{r}
t.cop <- tCopula(dim=2)
set.seed(500)

fit <- fitCopula(t.cop,m,method='ml')
coef(fit)

rho <- coef(fit)[1]
df <- coef(fit)[2]

```

```{r}

copula_dist <- mvdc(copula=tCopula(rho,dim=2,df=df), margins=c("t","t"),
                    paramMargins=list(list(df = df),
                                      list(df = df)))

sim1 <- rmvdc(copula_dist, 3466)
```

```{r}
c.cop <- claytonCopula(dim=2)
set.seed(500)

fit <- fitCopula(c.cop,m,method='ml')
coef(fit)
theta <- coef(fit)[1]
```


```{r}

copula_dist <- mvdc(copula=claytonCopula(theta,dim=2), margins=c("norm","norm"),
                    paramMargins=list(list(mean=mu.1, sd=sd.1),
                                      list(mean=mu.2, sd=sd.2)))

sim2 <- rmvdc(copula_dist, 3466)

```

```{r}
g.cop <- gumbelCopula(dim=2)
set.seed(500)
m <- pobs(as.matrix(cbind(rtns[,1],rtns[,3])))
fit <- fitCopula(g.cop,m,method='ml')
coef(fit)
theta <- coef(fit)[1]
```


```{r}

copula_dist <- mvdc(copula=gumbelCopula(theta,dim=2),margins=c("norm","norm"),
                    paramMargins=list(list(mean=mu.1, sd=sd.1),
                                      list(mean=mu.2, sd=sd.2)))

sim3 <- rmvdc(copula_dist, 3466)

```

```{r}

plot(a,b,main='normal-copula')
points(sim[,1],sim[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)
         
plot(a,b,main='t-copula')
points(sim1[,1],sim1[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)

plot(a,b,main='Clayton copula')
points(sim2[,1],sim2[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)

plot(a,b,main='Gumbel copula')
points(sim3[,1],sim3[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)

```

## DJIA,NDX
```{r}
a <- rtns[,1]
b <- rtns[,3]

m <- pobs(as.matrix(cbind(a,b)))

u <- m[,1]
v <- m[,2]

mu.1 <- mean(a)
sd.1 <- sd(a)
mu.2 <- mean(b)
sd.2 <- sd(b)

plot(a,b,pch='.')
abline(lm(a~b),col='red',lwd=1)

```


```{r}

selectedCopula <- BiCopSelect(u,v,familyset=NA)

summary(selectedCopula)

```

```{r}
n.cop <- normalCopula(dim=2)
set.seed(500)
fit <- fitCopula(n.cop,m,method='ml')
coef(fit)

rho <- coef(fit)[1]

```

```{r}

copula_dist <- mvdc(copula=normalCopula(rho,dim=2), margins=c("norm","norm"),
                    paramMargins=list(list(mean=mu.1, sd=sd.1),
                                      list(mean=mu.2, sd=sd.2)))

sim <- rmvdc(copula_dist, 3466)

```

```{r}
t.cop <- tCopula(dim=2)
set.seed(500)

fit <- fitCopula(t.cop,m,method='ml')
coef(fit)

rho <- coef(fit)[1]
df <- coef(fit)[2]

```

```{r}

copula_dist <- mvdc(copula=tCopula(rho,dim=2,df=df), margins=c("t","t"),
                    paramMargins=list(list(df=df),
                                      list(df=df)))

sim1 <- rmvdc(copula_dist, 3466)
```

```{r}
c.cop <- claytonCopula(dim=2)
set.seed(500)

fit <- fitCopula(c.cop,m,method='ml')
coef(fit)
theta <- coef(fit)[1]
```


```{r}

copula_dist <- mvdc(copula=claytonCopula(theta,dim=2), margins=c("norm","norm"),
                    paramMargins=list(list(mean=mu.1, sd=sd.1),
                                      list(mean=mu.2, sd=sd.2)))



sim2 <- rmvdc(copula_dist, 3466)

```

```{r}
g.cop <- gumbelCopula(dim=2)
set.seed(500)
m <- pobs(as.matrix(cbind(rtns[,1],rtns[,3])))
fit <- fitCopula(g.cop,m,method='ml')
coef(fit)
theta <- coef(fit)[1]
```


```{r}

copula_dist <- mvdc(copula=gumbelCopula(theta,dim=2), margins=c("norm","norm"),
                    paramMargins=list(list(mean=mu.1, sd=sd.1),
                                      list(mean=mu.2, sd=sd.2)))

sim3 <- rmvdc(copula_dist, 3466)

```

```{r}

plot(a,b,main='normal-copula')
points(sim[,1],sim[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)
         
plot(a,b,main='t-copula')
points(sim1[,1],sim1[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)

plot(a,b,main='Clayton copula')
points(sim2[,1],sim2[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)

plot(a,b,main='Gumbel copula')
points(sim3[,1],sim3[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)

```

## DJIA,GDAXI

```{r}
a <- rtns[,1]
b <- rtns[,4]

m <- pobs(as.matrix(cbind(a,b)))

u <- m[,1]
v <- m[,2]

mu.1 <- mean(a)
sd.1 <- sd(a)
mu.2 <- mean(b)
sd.2 <- sd(b)

plot(a,b,pch='.')
abline(lm(a~b),col='red',lwd=1)

```


```{r}

selectedCopula <- BiCopSelect(u,v,familyset=NA)

summary(selectedCopula)

```

```{r}
n.cop <- normalCopula(dim=2)
set.seed(500)
fit <- fitCopula(n.cop,m,method='ml')
coef(fit)

rho <- coef(fit)[1]

```

```{r}

copula_dist <- mvdc(copula=normalCopula(rho,dim=2), margins=c("norm","norm"),
                    paramMargins=list(list(mean=mu.1, sd=sd.1),
                                      list(mean=mu.2, sd=sd.2)))

sim <- rmvdc(copula_dist, 3466)

```

```{r}
t.cop <- tCopula(dim=2)
set.seed(500)

fit <- fitCopula(t.cop,m,method='ml')
coef(fit)

rho <- coef(fit)[1]
df <- coef(fit)[2]

```

```{r}

copula_dist <- mvdc(copula=tCopula(rho,dim=2,df=df), margins=c("t","t"),
                    paramMargins=list(list(df=df),
                                      list(df=df)))

sim1 <- rmvdc(copula_dist, 3466)
```

```{r}
c.cop <- claytonCopula(dim=2)
set.seed(500)

fit <- fitCopula(c.cop,m,method='ml')
coef(fit)
theta <- coef(fit)[1]
```


```{r}

copula_dist <- mvdc(copula=claytonCopula(theta,dim=2), margins=c("norm","norm"),
                    paramMargins=list(list(mean=mu.1, sd=sd.1),
                                      list(mean=mu.2, sd=sd.2)))



sim2 <- rmvdc(copula_dist, 3466)

```

```{r}
g.cop <- gumbelCopula(dim=2)
set.seed(500)
m <- pobs(as.matrix(cbind(rtns[,1],rtns[,3])))
fit <- fitCopula(g.cop,m,method='ml')
coef(fit)
theta <- coef(fit)[1]
```


```{r}

copula_dist <- mvdc(copula=gumbelCopula(theta,dim=2), margins=c("norm","norm"),
                    paramMargins=list(list(mean=mu.1, sd=sd.1),
                                      list(mean=mu.2, sd=sd.2)))

sim3 <- rmvdc(copula_dist, 3466)

```

```{r}

plot(a,b,main='normal-copula')
points(sim[,1],sim[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)
         
plot(a,b,main='t-copula')
points(sim1[,1],sim1[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)

plot(a,b,main='Clayton copula')
points(sim2[,1],sim2[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)

plot(a,b,main='Gumbel copula')
points(sim3[,1],sim3[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)
```

## DJIA,FCHI

```{r}
a <- rtns[,1]
b <- rtns[,5]

m <- pobs(as.matrix(cbind(a,b)))

u <- m[,1]
v <- m[,2]

mu.1 <- mean(a)
sd.1 <- sd(a)
mu.2 <- mean(b)
sd.2 <- sd(b)

plot(a,b,pch='.')
abline(lm(a~b),col='red',lwd=1)

```


```{r}

selectedCopula <- BiCopSelect(u,v,familyset=NA)

summary(selectedCopula)

```

```{r}
n.cop <- normalCopula(dim=2)
set.seed(500)
fit <- fitCopula(n.cop,m,method='ml')
coef(fit)

rho <- coef(fit)[1]

```

```{r}

copula_dist <- mvdc(copula=normalCopula(rho,dim=2), margins=c("norm","norm"),
                    paramMargins=list(list(mean=mu.1, sd=sd.1),
                                      list(mean=mu.2, sd=sd.2)))

sim <- rmvdc(copula_dist, 3466)

```

```{r}
t.cop <- tCopula(dim=2)
set.seed(500)

fit <- fitCopula(t.cop,m,method='ml')
coef(fit)

rho <- coef(fit)[1]
df <- coef(fit)[2]

```

```{r}

copula_dist <- mvdc(copula=tCopula(rho,dim=2,df=df), margins=c("t","t"),
                    paramMargins=list(list(df=df),
                                      list(df=df)))

sim1 <- rmvdc(copula_dist, 3466)
```

```{r}
c.cop <- claytonCopula(dim=2)
set.seed(500)

fit <- fitCopula(c.cop,m,method='ml')
coef(fit)
theta <- coef(fit)[1]
```


```{r}

copula_dist <- mvdc(copula=claytonCopula(theta,dim=2), margins=c("norm","norm"),
                    paramMargins=list(list(mean=mu.1, sd=sd.1),
                                      list(mean=mu.2, sd=sd.2)))



sim2 <- rmvdc(copula_dist, 3466)

```

```{r}
g.cop <- gumbelCopula(dim=2)
set.seed(500)
m <- pobs(as.matrix(cbind(rtns[,1],rtns[,3])))
fit <- fitCopula(g.cop,m,method='ml')
coef(fit)
theta <- coef(fit)[1]
```


```{r}

copula_dist <- mvdc(copula=gumbelCopula(theta,dim=2), margins=c("norm","norm"),
                    paramMargins=list(list(mean=mu.1, sd=sd.1),
                                      list(mean=mu.2, sd=sd.2)))

sim3 <- rmvdc(copula_dist, 3466)

```

```{r}

plot(a,b,main='normal-copula')
points(sim[,1],sim[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)
         
plot(a,b,main='t-copula')
points(sim1[,1],sim1[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)

plot(a,b,main='Clayton copula')
points(sim2[,1],sim2[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)

plot(a,b,main='Gumbel copula')
points(sim3[,1],sim3[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)
```

## DJIA,SSEC

```{r}
a <- rtns[,1]
b <- rtns[,6]

m <- pobs(as.matrix(cbind(a,b)))

u <- m[,1]
v <- m[,2]

mu.1 <- mean(a)
sd.1 <- sd(a)
mu.2 <- mean(b)
sd.2 <- sd(b)

plot(a,b,pch='.')
abline(lm(a~b),col='red',lwd=1)

```


```{r}

selectedCopula <- BiCopSelect(u,v,familyset=NA)

summary(selectedCopula)

```

```{r}
n.cop <- normalCopula(dim=2)
set.seed(500)
fit <- fitCopula(n.cop,m,method='ml')
coef(fit)

rho <- coef(fit)[1]

```

```{r}

copula_dist <- mvdc(copula=normalCopula(rho,dim=2), margins=c("norm","norm"),
                    paramMargins=list(list(mean=mu.1, sd=sd.1),
                                      list(mean=mu.2, sd=sd.2)))

sim <- rmvdc(copula_dist, 3466)

```

```{r}
t.cop <- tCopula(dim=2)
set.seed(500)

fit <- fitCopula(t.cop,m,method='ml')
coef(fit)

rho <- coef(fit)[1]
df <- coef(fit)[2]

```

```{r}

copula_dist <- mvdc(copula=tCopula(rho,dim=2,df=df), margins=c("t","t"),
                    paramMargins=list(list(df=df),
                                      list(df=df)))

sim1 <- rmvdc(copula_dist, 3466)
```

```{r}
c.cop <- claytonCopula(dim=2)
set.seed(500)

fit <- fitCopula(c.cop,m,method='ml')
coef(fit)
theta <- coef(fit)[1]
```


```{r}

copula_dist <- mvdc(copula=claytonCopula(theta,dim=2), margins=c("norm","norm"),
                    paramMargins=list(list(mean=mu.1, sd=sd.1),
                                      list(mean=mu.2, sd=sd.2)))



sim2 <- rmvdc(copula_dist, 3466)

```

```{r}
g.cop <- gumbelCopula(dim=2)
set.seed(500)
m <- pobs(as.matrix(cbind(rtns[,1],rtns[,3])))
fit <- fitCopula(g.cop,m,method='ml')
coef(fit)
theta <- coef(fit)[1]
```


```{r}

copula_dist <- mvdc(copula=gumbelCopula(theta,dim=2), margins=c("norm","norm"),
                    paramMargins=list(list(mean=mu.1, sd=sd.1),
                                      list(mean=mu.2, sd=sd.2)))

sim3 <- rmvdc(copula_dist, 3466)

```

```{r}

plot(a,b,main='normal-copula')
points(sim[,1],sim[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)
         
plot(a,b,main='t-copula')
points(sim1[,1],sim1[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)

plot(a,b,main='Clayton copula')
points(sim2[,1],sim2[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)

plot(a,b,main='Gumbel copula')
points(sim3[,1],sim3[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)
```

## DJIA,SENSEX

```{r}
a <- rtns[,1]
b <- rtns[,7]

m <- pobs(as.matrix(cbind(a,b)))

u <- m[,1]
v <- m[,2]

mu.1 <- mean(a)
sd.1 <- sd(a)
mu.2 <- mean(b)
sd.2 <- sd(b)

plot(a,b,pch='.')
abline(lm(a~b),col='red',lwd=1)

```


```{r}

selectedCopula <- BiCopSelect(u,v,familyset=NA)

summary(selectedCopula)

```

```{r}
n.cop <- normalCopula(dim=2)
set.seed(500)
fit <- fitCopula(n.cop,m,method='ml')
coef(fit)

rho <- coef(fit)[1]

```

```{r}

copula_dist <- mvdc(copula=normalCopula(rho,dim=2), margins=c("norm","norm"),
                    paramMargins=list(list(mean=mu.1, sd=sd.1),
                                      list(mean=mu.2, sd=sd.2)))

sim <- rmvdc(copula_dist, 3466)

```

```{r}
t.cop <- tCopula(dim=2)
set.seed(500)

fit <- fitCopula(t.cop,m,method='ml')
coef(fit)

rho <- coef(fit)[1]
df <- coef(fit)[2]

```

```{r}

copula_dist <- mvdc(copula=tCopula(rho,dim=2,df=df), margins=c("t","t"),
                    paramMargins=list(list(df=df),
                                      list(df=df)))

sim1 <- rmvdc(copula_dist, 3466)
```

```{r}
c.cop <- claytonCopula(dim=2)
set.seed(500)

fit <- fitCopula(c.cop,m,method='ml')
coef(fit)
theta <- coef(fit)[1]
```


```{r}

copula_dist <- mvdc(copula=claytonCopula(theta,dim=2), margins=c("norm","norm"),
                    paramMargins=list(list(mean=mu.1, sd=sd.1),
                                      list(mean=mu.2, sd=sd.2)))



sim2 <- rmvdc(copula_dist, 3466)

```

```{r}
g.cop <- gumbelCopula(dim=2)
set.seed(500)
m <- pobs(as.matrix(cbind(rtns[,1],rtns[,3])))
fit <- fitCopula(g.cop,m,method='ml')
coef(fit)
theta <- coef(fit)[1]
```


```{r}

copula_dist <- mvdc(copula=gumbelCopula(theta,dim=2), margins=c("norm","norm"),
                    paramMargins=list(list(mean=mu.1, sd=sd.1),
                                      list(mean=mu.2, sd=sd.2)))

sim3 <- rmvdc(copula_dist, 3466)

```

```{r}

plot(a,b,main='normal-copula')
points(sim[,1],sim[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)
         
plot(a,b,main='t-copula')
points(sim1[,1],sim1[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)

plot(a,b,main='Clayton copula')
points(sim2[,1],sim2[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)

plot(a,b,main='Gumbel copula')
points(sim3[,1],sim3[,2],col='red')
legend('bottomright',c('Observed','Simulated'),col=c('black','red'),pch=21)
```
